# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 633680a99232ccb52b91b5319bf62b988b2cadbc1700c40adfc743cc9015413578ff54d0b28ba8dba7a1cee01f05d4537c072f5628a3ec125e25baf07fad366f

test:
  secret_key_base: cf01bfe768dd75aa69ebf49012d3d71b3b278b605f633788f0870cb64eec0e7ab82f6a12742a76cc65e60f052cbe9eecab1b54ffb459ddc13377edad0954b230

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
